CREATE TABLE [dbo].[Logement]
(
	[IdLogement] INT IDENTITY NOT NULL, 
    [prix] MONEY NOT NULL, 
    [nom] NVARCHAR(50) NOT NULL, 
    [adresseRue] NVARCHAR(255) NOT NULL, 
    [adresseNumero] NVARCHAR(15) NOT NULL, 
    [adresseCodePostal] NVARCHAR(8) NOT NULL, 
    [adressePays] NVARCHAR(50) NOT NULL, 
    [longitude] DECIMAL(10,7) NOT NULL,
    [latitude] DECIMAL(10,7) NOT NULL,
    [desc_courte] NVARCHAR(100) NOT NULL, 
    [desc_longue] NVARCHAR(MAX) NOT NULL, 
    [nb_chambre] TINYINT NOT NULL DEFAULT 0, 
    [nb_piece] TINYINT NOT NULL DEFAULT 1, 
    [nb_sdb] TINYINT NOT NULL DEFAULT 1, 
    [nb_wc] TINYINT NOT NULL DEFAULT 1, 
    [capacite] TINYINT NOT NULL DEFAULT 1, 
    [balcon] BIT NOT NULL DEFAULT 0, 
    [airco] BIT NOT NULL DEFAULT 0, 
    [wifi] BIT NOT NULL DEFAULT 0, 
    [minibar] BIT NOT NULL DEFAULT 0, 
    [animaux] BIT NOT NULL DEFAULT 0, 
    [piscine] BIT NOT NULL DEFAULT 0, 
    [voiturier] BIT NOT NULL DEFAULT 0, 
    [roomService] BIT NOT NULL DEFAULT 0,
    [idProprio] INT NOT NULL,
    CONSTRAINT [PK_logement] PRIMARY KEY ([IdLogement]),
    CONSTRAINT [CK_Logement_desc_courte] CHECK (LEN([desc_courte]) >= 100),
    CONSTRAINT [CK_Logement_desc_longue] CHECK (LEN([desc_longue]) >= LEN([desc_courte])),
    CONSTRAINT FK_Logement_Proprio FOREIGN KEY ([idProprio]) REFERENCES [Proprio]([idClient])
)
